// Generates protocol/golden-vectors-v1.json from the REAL firmware codec.
// The iOS SpoolDryKit tests decode/encode the same bytes, proving both sides agree byte-for-byte.
#include <cstdio>
#include <string>

#include "../../SpoolDry/src/core/Bytes.h"
#include "../../SpoolDry/src/core/Protocol.h"

using namespace spooldry;

static std::string hex(const uint8_t* b, size_t n) {
    static const char* d = "0123456789abcdef";
    std::string s;
    for (size_t i = 0; i < n; ++i) {
        s.push_back(d[b[i] >> 4]);
        s.push_back(d[b[i] & 15]);
    }
    return s;
}

int main(int argc, char** argv) {
    const char* path = argc > 1 ? argv[1] : "golden-vectors-v1.json";
    FILE* f = std::fopen(path, "w");
    if (!f) return 1;
    uint8_t b[64];
    size_t n;

    Snapshot s;
    s.state = DeviceState::DRYING;
    s.error = ErrorCode::NONE;
    s.flags = StatusFlag::HEATER_RELAY | StatusFlag::HEATER_OUTPUT | StatusFlag::FAN_ON | StatusFlag::CLIENT_CONNECTED |
              StatusFlag::CHAMBER_SENSOR_OK | StatusFlag::HEATER_SENSOR_OK | StatusFlag::SESSION_ACTIVE | StatusFlag::TIME_SYNCED;
    s.chamberCentiC = 6720;
    s.humidityCentiRh = 1840;
    s.heaterCentiC = 7105;
    s.targetCentiC = 7000;
    s.remainingSec = 9660;
    s.elapsedDryingSec = 19140;
    s.sessionId = 42;
    s.material = Material::PA_CF;
    s.heaterDuty = 37;
    s.fanRpm = 6800;
    s.uptimeSec = 23456;
    s.fanMode = FanMode::AUTO;
    s.endReason = EndReason::NONE;
    s.statusSeq = 513;
    s.durationSec = 28800;
    s.startUnixTime = 1790000000u;
    s.fanOn = true;
    s.relayOn = true;
    s.heaterOutputOn = true;

    std::fprintf(f, "{\n  \"protocolVersion\": %d,\n", kProtocolVersion);
    std::fprintf(f, "  \"note\": \"Generated by esp32/test/host/golden_vectors.cpp from the firmware codec. Do not edit.\",\n");
    std::fprintf(f, "  \"snapshot\": {\"state\": 5, \"error\": 0, \"flags\": 255, \"chamberCentiC\": 6720, \"humidityCentiRh\": 1840, \"heaterCentiC\": 7105, \"targetCentiC\": 7000, \"remainingSec\": 9660, \"elapsedDryingSec\": 19140, \"sessionId\": 42, \"material\": 13, \"heaterDuty\": 37, \"fanRpm\": 6800, \"uptimeSec\": 23456, \"fanMode\": 0, \"endReason\": 0, \"statusSeq\": 513, \"durationSec\": 28800, \"startUnixTime\": 1790000000},\n");
    n = encodeDeviceStatus(s, b, sizeof b);
    std::fprintf(f, "  \"deviceStatus\": \"%s\",\n", hex(b, n).c_str());
    n = encodeTemperature(s, b, sizeof b);
    std::fprintf(f, "  \"temperature\": \"%s\",\n", hex(b, n).c_str());
    n = encodeHumidity(s, b, sizeof b);
    std::fprintf(f, "  \"humidity\": \"%s\",\n", hex(b, n).c_str());
    n = encodeHeaterState(s, b, sizeof b);
    std::fprintf(f, "  \"heaterState\": \"%s\",\n", hex(b, n).c_str());
    n = encodeFanState(s, b, sizeof b);
    std::fprintf(f, "  \"fanState\": \"%s\",\n", hex(b, n).c_str());
    n = encodeDryingSession(s, b, sizeof b);
    std::fprintf(f, "  \"dryingSession\": \"%s\",\n", hex(b, n).c_str());
    n = encodeTargetTemp(s, b, sizeof b);
    std::fprintf(f, "  \"targetTemp\": \"%s\",\n", hex(b, n).c_str());
    n = encodeRemainingTime(s, b, sizeof b);
    std::fprintf(f, "  \"remainingTime\": \"%s\",\n", hex(b, n).c_str());

    Snapshot inv;  // invalid sensors, idle
    n = encodeDeviceStatus(inv, b, sizeof b);
    std::fprintf(f, "  \"deviceStatusInvalidSensors\": \"%s\",\n", hex(b, n).c_str());

    DeviceInfo info;
    const uint8_t id[6] = {0x40, 0x4C, 0xCA, 0x12, 0xA1, 0xB2};
    for (int i = 0; i < 6; ++i) info.deviceId[i] = id[i];
    info.capabilities = Capability::HEATER_NTC | Capability::FAN_TACH | Capability::SAFETY_RELAY |
                        Capability::IDENTIFY_LED | Capability::LOCAL_BUTTON;
    info.resetReason = static_cast<uint8_t>(ResetCause::POWER_ON);
    info.lastFault = 0;
    n = encodeDeviceInfo(info, b, sizeof b);
    std::fprintf(f, "  \"deviceInfo\": \"%s\",\n", hex(b, n).c_str());
    std::fprintf(f, "  \"deviceInfoFields\": {\"deviceId\": \"404cca12a1b2\", \"capabilities\": %u, \"resetReason\": 1},\n", info.capabilities);

    // Commands
    std::fprintf(f, "  \"commands\": {\n");
    {
        uint8_t p[12];
        ByteWriter w(p, sizeof p);
        w.u8(static_cast<uint8_t>(Material::PA_CF));
        w.i16(7000);
        w.u32(28800);
        w.u32(1790000000u);
        w.u8(static_cast<uint8_t>(FanMode::AUTO));
        n = encodeCommandFrame(Opcode::START_SESSION, 1, p, static_cast<uint8_t>(w.size()), b, sizeof b);
        std::fprintf(f, "    \"startSession\": \"%s\",\n", hex(b, n).c_str());
    }
    n = encodeCommandFrame(Opcode::STOP_SESSION, 2, nullptr, 0, b, sizeof b);
    std::fprintf(f, "    \"stopSession\": \"%s\",\n", hex(b, n).c_str());
    {
        uint8_t p[2] = {0x94, 0x11};  // 4500
        n = encodeCommandFrame(Opcode::SET_TARGET_TEMP, 3, p, 2, b, sizeof b);
        std::fprintf(f, "    \"setTargetTemp4500\": \"%s\",\n", hex(b, n).c_str());
    }
    {
        uint8_t p[4] = {0x10, 0x0E, 0x00, 0x00};  // 3600
        n = encodeCommandFrame(Opcode::SET_DURATION, 4, p, 4, b, sizeof b);
        std::fprintf(f, "    \"setDuration3600\": \"%s\",\n", hex(b, n).c_str());
    }
    {
        uint8_t p[1] = {static_cast<uint8_t>(Material::PETG)};
        n = encodeCommandFrame(Opcode::SET_FILAMENT, 5, p, 1, b, sizeof b);
        std::fprintf(f, "    \"setFilamentPetg\": \"%s\",\n", hex(b, n).c_str());
    }
    {
        uint8_t p[1] = {static_cast<uint8_t>(FanMode::ON)};
        n = encodeCommandFrame(Opcode::SET_FAN_MODE, 6, p, 1, b, sizeof b);
        std::fprintf(f, "    \"setFanModeOn\": \"%s\",\n", hex(b, n).c_str());
    }
    n = encodeCommandFrame(Opcode::REQUEST_STATUS, 7, nullptr, 0, b, sizeof b);
    std::fprintf(f, "    \"requestStatus\": \"%s\",\n", hex(b, n).c_str());
    n = encodeCommandFrame(Opcode::RESET_SESSION, 8, nullptr, 0, b, sizeof b);
    std::fprintf(f, "    \"resetSession\": \"%s\",\n", hex(b, n).c_str());
    n = encodeCommandFrame(Opcode::IDENTIFY, 9, nullptr, 0, b, sizeof b);
    std::fprintf(f, "    \"identify\": \"%s\",\n", hex(b, n).c_str());
    {
        const uint8_t p[] = {'L', 'a', 'b', ' ', 'D', 'r', 'y', 'e', 'r'};
        n = encodeCommandFrame(Opcode::SET_DEVICE_NAME, 10, p, sizeof p, b, sizeof b);
        std::fprintf(f, "    \"setDeviceNameLabDryer\": \"%s\"\n", hex(b, n).c_str());
    }
    std::fprintf(f, "  },\n");

    // Responses
    Response ack;
    ack.type = ResponseType::ACK;
    ack.seq = 1;
    ack.opcode = static_cast<uint8_t>(Opcode::START_SESSION);
    ack.result = ResultCode::OK;
    {
        ByteWriter w(ack.payload, sizeof ack.payload);
        w.u32(42);
        w.u32(1790000000u);
        ack.payloadLen = static_cast<uint8_t>(w.size());
    }
    n = encodeResponse(ack, b, sizeof b);
    std::fprintf(f, "  \"responseStartAck\": \"%s\",\n", hex(b, n).c_str());
    Response nack;
    nack.type = ResponseType::NACK;
    nack.seq = 9;
    nack.opcode = static_cast<uint8_t>(Opcode::START_SESSION);
    nack.result = ResultCode::NOT_ALLOWED_IN_STATE;
    nack.payload[0] = static_cast<uint8_t>(DeviceState::OVER_TEMPERATURE);
    nack.payload[1] = static_cast<uint8_t>(ErrorCode::OVER_TEMP_CHAMBER);
    nack.payloadLen = 2;
    n = encodeResponse(nack, b, sizeof b);
    std::fprintf(f, "  \"responseStartNackOverTemp\": \"%s\"\n", hex(b, n).c_str());
    std::fprintf(f, "}\n");
    std::fclose(f);
    std::printf("wrote %s\n", path);
    return 0;
}
