# -*- coding: utf-8 -*-
"""Localized website copy. Each value: dict lang -> text."""

LANGS = ["en", "de", "fr", "es", "ar", "ja"]
LANG_NAMES = {"en": "English", "de": "Deutsch", "fr": "Français", "es": "Español", "ar": "العربية", "ja": "日本語"}
HREFLANG = {"en": "en", "de": "de", "fr": "fr", "es": "es", "ar": "ar", "ja": "ja"}
OG_LOCALE = {"en": "en_US", "de": "de_DE", "fr": "fr_FR", "es": "es_ES", "ar": "ar_SA", "ja": "ja_JP"}


def L(en, de, fr, es, ar, ja):
    return {"en": en, "de": de, "fr": fr, "es": es, "ar": ar, "ja": ja}


C = {
"title": L("SpoolDry – ESP32 Filament Dryer App for iPhone | Temperature & Humidity",
           "SpoolDry – ESP32-Filamenttrockner-App fürs iPhone | Temperatur & Feuchte",
           "SpoolDry – App de sécheur de filament ESP32 pour iPhone | Température & humidité",
           "SpoolDry – App de secador de filamento ESP32 para iPhone | Temperatura y humedad",
           "SpoolDry – تطبيق مجفف خيوط ESP32 لجهاز iPhone | الحرارة والرطوبة",
           "SpoolDry – iPhone用ESP32フィラメントドライヤーアプリ｜温度と湿度"),
"description": L("Connect your ESP32 filament dryer to your iPhone over Bluetooth. Live temperature and humidity, Live Activity drying timer, engineering polymer profiles, open firmware and BOM. 3 bakes free, $19.99 lifetime.",
                 "Verbinde deinen ESP32-Filamenttrockner per Bluetooth mit dem iPhone. Temperatur und Feuchte live, Live-Aktivität, Profile für technische Kunststoffe, offene Firmware und Stückliste. 3 Trocknungen gratis.",
                 "Reliez votre sécheur de filament ESP32 à l'iPhone en Bluetooth. Température et humidité en direct, activité en direct, profils de polymères techniques, firmware et nomenclature ouverts. 3 séchages offerts.",
                 "Conecta tu secador de filamento ESP32 al iPhone por Bluetooth. Temperatura y humedad en vivo, Actividad en vivo, perfiles de polímeros técnicos, firmware y lista de materiales abiertos. 3 secados gratis.",
                 "اربط مجفف الخيوط ESP32 بجهاز iPhone عبر البلوتوث. حرارة ورطوبة مباشرة ونشاط مباشر وملفات للبوليمرات الهندسية وبرنامج ثابت وقائمة مكونات مفتوحة. 3 جلسات مجانًا.",
                 "ESP32フィラメントドライヤーをBluetoothでiPhoneに接続。温度と湿度をリアルタイム表示、ライブアクティビティ、エンジニアリングポリマーのプロファイル、オープンなファームウェアと部品表。3回無料。"),
"nav_features": L("Features", "Funktionen", "Fonctions", "Funciones", "الميزات", "機能"),
"nav_build": L("Build", "Bauen", "Montage", "Montaje", "التجميع", "組み立て"),
"nav_setup": L("ESP32 Setup", "ESP32-Setup", "Config. ESP32", "Config. ESP32", "إعداد ESP32", "ESP32設定"),
"nav_filament": L("Filament data", "Filamentdaten", "Données filament", "Datos de filamento", "بيانات الخيوط", "フィラメント"),
"nav_safety": L("Safety", "Sicherheit", "Sécurité", "Seguridad", "السلامة", "安全"),
"nav_pricing": L("Pricing", "Preis", "Tarif", "Precio", "السعر", "料金"),
"nav_faq": L("FAQ", "FAQ", "FAQ", "FAQ", "الأسئلة", "FAQ"),
"theme": L("Toggle light/dark mode", "Hell/Dunkel umschalten", "Basculer clair/sombre", "Cambiar claro/oscuro", "تبديل الوضع الفاتح/الداكن", "ライト/ダークを切り替え"),
"hero_kicker": L("ESP32 · Bluetooth LE · iPhone", "ESP32 · Bluetooth LE · iPhone", "ESP32 · Bluetooth LE · iPhone", "ESP32 · Bluetooth LE · iPhone", "ESP32 · Bluetooth LE · iPhone", "ESP32 · Bluetooth LE · iPhone"),
"hero_h1": L("Know your filament.<br>Know its moisture.", "Kenne dein Filament.<br>Kenne seine Feuchte.", "Connaissez votre filament.<br>Connaissez son humidité.", "Conoce tu filamento.<br>Conoce su humedad.", "اعرف خيطك.<br>اعرف رطوبته.", "フィラメントを知る。<br>その湿度を知る。"),
"hero_p": L("SpoolDry connects your filament dryer to your iPhone using Bluetooth. Watch temperature and humidity live, start drying with engineering-polymer profiles and follow the timer on your Lock Screen. No account. No cloud.",
            "SpoolDry verbindet deinen Filamenttrockner per Bluetooth mit dem iPhone. Temperatur und Feuchte live, Trocknung mit Profilen für technische Kunststoffe starten, Timer auf dem Sperrbildschirm. Kein Konto. Keine Cloud.",
            "SpoolDry relie votre sécheur de filament à l'iPhone en Bluetooth. Suivez température et humidité en direct, lancez un séchage avec des profils de polymères techniques et suivez le minuteur sur l'écran verrouillé. Sans compte. Sans cloud.",
            "SpoolDry conecta tu secador de filamento al iPhone por Bluetooth. Mira la temperatura y la humedad en vivo, inicia el secado con perfiles de polímeros técnicos y sigue el temporizador en la pantalla bloqueada. Sin cuenta. Sin nube.",
            "يربط SpoolDry مجفف الخيوط بجهاز iPhone عبر البلوتوث. شاهد الحرارة والرطوبة مباشرة، وابدأ التجفيف بملفات البوليمرات الهندسية، وتابع المؤقت على شاشة القفل. بلا حساب. بلا سحابة.",
            "SpoolDryはフィラメントドライヤーとiPhoneをBluetoothで接続。温度と湿度をリアルタイムで確認し、エンジニアリングポリマーのプロファイルで乾燥を開始、ロック画面でタイマーを確認。アカウント不要、クラウドなし。"),
"cta_free": L("Track 3 Bakes Free", "3 Trocknungen gratis", "3 séchages offerts", "3 secados gratis", "3 جلسات تجفيف مجانًا", "3回無料で記録"),
"cta_life": L("$19.99 Lifetime", "Lifetime einmalig", "Achat unique à vie", "Compra única de por vida", "شراء لمرة واحدة", "買い切りライセンス"),
"no_sub": L("No subscription. One-time purchase.", "Kein Abo. Einmalkauf.", "Sans abonnement. Achat unique.", "Sin suscripción. Compra única.", "بدون اشتراك. شراء لمرة واحدة.", "サブスクなし。買い切り。"),
"appstore": L("Coming to the App Store", "Bald im App Store", "Bientôt sur l'App Store", "Próximamente en el App Store", "قريبًا على App Store", "App Storeで近日公開"),
"features_h": L("Everything your dryer was missing", "Alles, was deinem Trockner fehlte", "Tout ce qui manquait à votre sécheur", "Todo lo que le faltaba a tu secador", "كل ما كان ينقص مجففك", "ドライヤーに足りなかったすべて"),
"b_ble_h": L("ESP32 BLE Sync", "ESP32-BLE-Sync", "Synchro ESP32 BLE", "Sincronía ESP32 BLE", "مزامنة ESP32 عبر BLE", "ESP32 BLE同期"),
"b_ble_p": L("Direct, paired Bluetooth LE link to the ESP32. Versioned protocol with acknowledged commands: the app always shows the dryer's real state.", "Direkte, gekoppelte Bluetooth-LE-Verbindung zum ESP32. Versioniertes Protokoll mit bestätigten Befehlen: Die App zeigt immer den echten Zustand.", "Liaison Bluetooth LE directe et jumelée avec l'ESP32. Protocole versionné à commandes acquittées : l'app montre toujours l'état réel.", "Enlace Bluetooth LE directo y emparejado con el ESP32. Protocolo versionado con comandos confirmados: la app muestra siempre el estado real.", "اتصال Bluetooth LE مباشر ومقترن مع ESP32. بروتوكول بإصدارات وأوامر مؤكدة: يعرض التطبيق دائمًا الحالة الفعلية.", "ESP32とのペアリング済みBluetooth LE直接接続。確認応答付きのバージョン管理プロトコルで、常に実際の状態を表示。"),
"b_poly_h": L("Engineering Polymers Data", "Daten für technische Kunststoffe", "Données polymères techniques", "Datos de polímeros técnicos", "بيانات البوليمرات الهندسية", "エンジニアリングポリマーのデータ"),
"b_poly_p": L("PLA to PEEK, PA-CF and PPS: typical starting guidance with manufacturer sources, never presented as an official requirement.", "Von PLA bis PEEK, PA-CF und PPS: typische Startwerte mit Herstellerquellen, nie als offizielle Vorgabe dargestellt.", "Du PLA au PEEK, PA-CF et PPS : repères typiques avec sources fabricants, jamais présentés comme exigence officielle.", "De PLA a PEEK, PA-CF y PPS: pautas típicas con fuentes de fabricantes, nunca presentadas como requisito oficial.", "من PLA إلى PEEK وPA-CF وPPS: إرشادات نموذجية مع مصادر المصنّعين، ولا تُعرض كمتطلبات رسمية.", "PLAからPEEK、PA-CF、PPSまで。メーカー出典付きの一般的な初期目安で、公式要件としては扱いません。"),
"b_live_h": L("Live Activity Timers", "Live-Aktivitäts-Timer", "Minuteurs en activité en direct", "Temporizadores en Actividad en vivo", "مؤقتات النشاط المباشر", "ライブアクティビティタイマー"),
"b_live_p": L("Lock Screen and Dynamic Island show filament, target, current temperature, humidity and remaining time, straight from the device.", "Sperrbildschirm und Dynamic Island zeigen Filament, Ziel, aktuelle Temperatur, Feuchte und Restzeit direkt vom Gerät.", "Écran verrouillé et Dynamic Island affichent filament, cible, température, humidité et temps restant, directement depuis l'appareil.", "La pantalla bloqueada y la Dynamic Island muestran filamento, objetivo, temperatura, humedad y tiempo restante, directo del dispositivo.", "شاشة القفل والجزيرة الديناميكية تعرضان الخيط والهدف والحرارة والرطوبة والوقت المتبقي مباشرة من الجهاز.", "ロック画面とDynamic Islandにフィラメント、目標、現在温度、湿度、残り時間をデバイスから直接表示。"),
"b_cloud_h": L("Zero Cloud Setup", "Null Cloud-Einrichtung", "Zéro cloud", "Cero nube", "بلا سحابة", "クラウド設定ゼロ"),
"b_cloud_p": L("No account, no server, no internet. Everything stays between your iPhone and your dryer.", "Kein Konto, kein Server, kein Internet. Alles bleibt zwischen iPhone und Trockner.", "Pas de compte, pas de serveur, pas d'internet. Tout reste entre l'iPhone et le sécheur.", "Sin cuenta, sin servidor, sin internet. Todo queda entre tu iPhone y tu secador.", "بلا حساب ولا خادم ولا إنترنت. كل شيء يبقى بين الـ iPhone والمجفف.", "アカウントもサーバーもインターネットも不要。すべてiPhoneとドライヤーの間だけ。"),
"b_th_h": L("Temperature & Humidity", "Temperatur & Feuchte", "Température & humidité", "Temperatura y humedad", "الحرارة والرطوبة", "温度と湿度"),
"b_th_p": L("Sensirion SHT40 accuracy with live charts.", "Sensirion-SHT40-Genauigkeit mit Live-Diagrammen.", "Précision Sensirion SHT40 et graphiques en direct.", "Precisión Sensirion SHT40 con gráficos en vivo.", "دقة Sensirion SHT40 مع مخططات مباشرة.", "Sensirion SHT40の精度とリアルタイムグラフ。"),
"b_prof_h": L("Smart Drying Profiles", "Smarte Trocknungsprofile", "Profils de séchage", "Perfiles de secado", "ملفات تجفيف ذكية", "スマート乾燥プロファイル"),
"b_prof_p": L("Built-in guidance plus your own brand profiles.", "Eingebaute Richtwerte plus eigene Markenprofile.", "Repères intégrés et vos propres profils de marque.", "Pautas integradas y tus propios perfiles de marca.", "إرشادات مدمجة مع ملفات علاماتك الخاصة.", "内蔵の目安と独自ブランドのプロファイル。"),
"b_hist_h": L("Offline History", "Offline-Verlauf", "Historique hors ligne", "Historial sin conexión", "سجل دون اتصال", "オフライン履歴"),
"b_hist_p": L("Start/end humidity, average temperature, charts and statistics.", "Start-/Endfeuchte, Durchschnittstemperatur, Diagramme und Statistiken.", "Humidité initiale/finale, température moyenne, graphiques et statistiques.", "Humedad inicial/final, temperatura media, gráficos y estadísticas.", "الرطوبة الأولية/النهائية ومتوسط الحرارة والمخططات والإحصاءات.", "開始/終了湿度、平均温度、グラフと統計。"),
"b_safe_h": L("Safety Monitoring", "Sicherheitsüberwachung", "Surveillance de sécurité", "Supervisión de seguridad", "مراقبة السلامة", "安全監視"),
"b_safe_p": L("Firmware limits, watchdog, fan tach, relay, thermostat and thermal fuse.", "Firmware-Grenzen, Watchdog, Lüfter-Tacho, Relais, Thermostat und Thermosicherung.", "Limites firmware, watchdog, tachymètre, relais, thermostat et fusible thermique.", "Límites de firmware, watchdog, tacómetro, relé, termostato y fusible térmico.", "حدود البرنامج الثابت ومؤقت الحراسة ومقياس المروحة والمرحّل والترموستات والمصهر الحراري.", "ファームウェア制限、ウォッチドッグ、ファン回転監視、リレー、サーモスタット、温度ヒューズ。"),
"b_multi_h": L("Multiple Devices", "Mehrere Geräte", "Plusieurs appareils", "Varios dispositivos", "عدة أجهزة", "複数デバイス"),
"b_multi_p": L("Name and switch between SpoolDry #1, #2 and more.", "Benenne SpoolDry #1, #2 und mehr und wechsle zwischen ihnen.", "Nommez SpoolDry #1, #2 et plus, et passez de l'un à l'autre.", "Nombra SpoolDry #1, #2 y más, y cambia entre ellos.", "سمِّ SpoolDry #1 و#2 وغيرها وتنقّل بينها.", "SpoolDry #1、#2…に名前を付けて切り替え。"),
"b_life_h": L("Lifetime Access", "Lifetime-Zugang", "Accès à vie", "Acceso de por vida", "وصول مدى الحياة", "永久アクセス"),
"b_life_p": L("Pay once. Every future improvement included.", "Einmal zahlen. Alle künftigen Verbesserungen inklusive.", "Payez une fois. Toutes les améliorations futures incluses.", "Paga una vez. Todas las mejoras futuras incluidas.", "ادفع مرة واحدة. كل التحسينات المستقبلية مشمولة.", "一度の支払いで今後の改善もすべて含む。"),
"build_h": L("Build Your SpoolDry", "Baue deinen SpoolDry", "Construisez votre SpoolDry", "Construye tu SpoolDry", "ابنِ SpoolDry الخاص بك", "SpoolDryを組み立てる"),
"build_p": L("A low-voltage (24 V DC) architecture: all mains voltage stays inside a certified, enclosed power adapter. The chamber is limited to 70 °C by the fan rating; independent hardware protects against software faults.",
             "Eine Niederspannungs-Architektur (24 V DC): Netzspannung bleibt im zertifizierten, geschlossenen Netzteil. Die Kammer ist durch den Lüfter auf 70 °C begrenzt; unabhängige Hardware schützt vor Softwarefehlern.",
             "Architecture basse tension (24 V CC) : la tension secteur reste dans un bloc d'alimentation certifié et fermé. La chambre est limitée à 70 °C par le ventilateur ; un matériel indépendant protège des défauts logiciels.",
             "Arquitectura de baja tensión (24 V CC): la tensión de red queda dentro de un adaptador certificado y cerrado. La cámara se limita a 70 °C por el ventilador; hardware independiente protege ante fallos de software.",
             "بنية جهد منخفض (24 V تيار مستمر): يبقى جهد الشبكة داخل محول طاقة معتمد ومغلق. تُحد الحجرة عند 70 °C بسبب تصنيف المروحة، ويحمي عتاد مستقل من أعطال البرمجيات.",
             "低電圧（24 V DC）構成。商用電源は認証済みの密閉型アダプター内部のみ。庫内はファン定格により70 °Cに制限され、独立したハードウェアがソフトウェアの故障から保護します。"),
"col_component": L("Component", "Bauteil", "Composant", "Componente", "المكون", "部品"),
"col_part": L("Selected part", "Gewähltes Teil", "Pièce choisie", "Pieza elegida", "القطعة المختارة", "選定部品"),
"col_purpose": L("Purpose", "Zweck", "Rôle", "Función", "الغرض", "用途"),
"col_spec": L("Recommended specification", "Empfohlene Spezifikation", "Spécification recommandée", "Especificación recomendada", "المواصفات الموصى بها", "推奨仕様"),
"col_why": L("Why it is used", "Warum", "Pourquoi", "Por qué", "سبب الاستخدام", "採用理由"),
"col_qty": L("Qty", "Anz.", "Qté", "Cant.", "الكمية", "数量"),
"col_links": L("Example links", "Beispiel-Links", "Liens d'exemple", "Enlaces de ejemplo", "روابط مثال", "購入例リンク"),
"bom_h": L("Bill of Materials", "Stückliste", "Nomenclature", "Lista de materiales", "قائمة المكونات", "部品表 (BOM)"),
"bom_note": L("Links are examples verified during research (October 2026); availability changes. Equivalent parts with the same ratings work.", "Links sind Beispiele, geprüft im Oktober 2026; die Verfügbarkeit ändert sich. Gleichwertige Teile mit denselben Werten funktionieren.", "Liens d'exemple vérifiés en octobre 2026 ; la disponibilité évolue. Des pièces équivalentes conviennent.", "Enlaces de ejemplo verificados en octubre de 2026; la disponibilidad cambia. Sirven piezas equivalentes.", "الروابط أمثلة تم التحقق منها في أكتوبر 2026؛ يتغير التوفر. تعمل القطع المكافئة بنفس التصنيفات.", "リンクは2026年10月に確認した購入例です。在庫は変動します。同等定格の部品で代替可能です。"),
"wiring_h": L("Wiring diagram", "Schaltplan", "Schéma de câblage", "Esquema de cableado", "مخطط التوصيل", "配線図"),
"pinout_h": L("ESP32-C6 pin map", "ESP32-C6-Pinbelegung", "Brochage ESP32-C6", "Pines del ESP32-C6", "توزيع منافذ ESP32-C6", "ESP32-C6ピン配置"),
"setup_h": L("ESP32 Setup", "ESP32-Setup", "Configuration de l'ESP32", "Configuración del ESP32", "إعداد ESP32", "ESP32のセットアップ"),
"setup_steps": L(
  ["Required hardware", "Install Arduino IDE or PlatformIO", "Install ESP32 board support", "Connect USB", "Select board", "Select port", "Install required libraries", "Compile firmware", "Flash firmware", "Open Serial Monitor", "Verify BLE advertising", "Open the SpoolDry iOS app", "Connect device"],
  ["Benötigte Hardware", "Arduino IDE oder PlatformIO installieren", "ESP32-Board-Support installieren", "USB verbinden", "Board wählen", "Port wählen", "Bibliotheken installieren", "Firmware kompilieren", "Firmware flashen", "Seriellen Monitor öffnen", "BLE-Advertising prüfen", "SpoolDry-App öffnen", "Gerät verbinden"],
  ["Matériel requis", "Installer Arduino IDE ou PlatformIO", "Installer le support ESP32", "Brancher l'USB", "Choisir la carte", "Choisir le port", "Installer les bibliothèques", "Compiler le firmware", "Flasher le firmware", "Ouvrir le moniteur série", "Vérifier l'annonce BLE", "Ouvrir l'app SpoolDry", "Connecter l'appareil"],
  ["Hardware necesario", "Instalar Arduino IDE o PlatformIO", "Instalar soporte ESP32", "Conectar USB", "Elegir placa", "Elegir puerto", "Instalar bibliotecas", "Compilar firmware", "Grabar firmware", "Abrir monitor serie", "Verificar anuncio BLE", "Abrir la app SpoolDry", "Conectar dispositivo"],
  ["العتاد المطلوب", "تثبيت Arduino IDE أو PlatformIO", "تثبيت دعم لوحات ESP32", "توصيل USB", "اختيار اللوحة", "اختيار المنفذ", "تثبيت المكتبات", "ترجمة البرنامج الثابت", "تحميل البرنامج الثابت", "فتح الشاشة التسلسلية", "التحقق من إعلان BLE", "فتح تطبيق SpoolDry", "توصيل الجهاز"],
  ["必要なハードウェア", "Arduino IDEまたはPlatformIOをインストール", "ESP32ボードサポートをインストール", "USBを接続", "ボードを選択", "ポートを選択", "ライブラリをインストール", "ファームウェアをコンパイル", "ファームウェアを書き込み", "シリアルモニターを開く", "BLEアドバタイズを確認", "SpoolDryアプリを開く", "デバイスを接続"]),
"fw_h": L("Firmware download", "Firmware-Download", "Téléchargement du firmware", "Descarga del firmware", "تنزيل البرنامج الثابت", "ファームウェアのダウンロード"),
"fw_btn": L("Download firmware source (.zip)", "Firmware-Quellcode laden (.zip)", "Télécharger les sources (.zip)", "Descargar código fuente (.zip)", "تنزيل الشيفرة المصدرية (.zip)", "ソースコードをダウンロード（.zip）"),
"fil_h": L("Typical drying guidance", "Typische Trocknungswerte", "Repères de séchage typiques", "Pautas de secado típicas", "إرشادات التجفيف النموذجية", "一般的な乾燥目安"),
"fil_note": L("Typical starting guidance compiled from official manufacturer pages, not a universal requirement. Always follow your filament's data sheet. SpoolDry hardware v1 reaches 70 °C.",
              "Typische Startwerte aus offiziellen Herstellerseiten, keine allgemeine Vorgabe. Folge immer dem Datenblatt deines Filaments. SpoolDry-Hardware v1 erreicht 70 °C.",
              "Repères de départ typiques issus des pages officielles des fabricants, pas une exigence universelle. Suivez toujours la fiche technique. Le matériel SpoolDry v1 atteint 70 °C.",
              "Pautas iniciales típicas de páginas oficiales de fabricantes, no un requisito universal. Sigue siempre la ficha técnica. El hardware SpoolDry v1 llega a 70 °C.",
              "إرشادات بداية نموذجية من صفحات المصنّعين الرسمية وليست متطلبات عامة. اتبع دائمًا ورقة بيانات الخيط. يصل عتاد SpoolDry v1 إلى 70 °C.",
              "公式メーカーページをもとにした一般的な初期目安で、普遍的な要件ではありません。必ずデータシートに従ってください。SpoolDryハードウェアv1は70 °Cまで。"),
"col_material": L("Material", "Material", "Matériau", "Material", "المادة", "素材"),
"col_temp": L("Typical temperature", "Typische Temperatur", "Température typique", "Temperatura típica", "الحرارة النموذجية", "一般的な温度"),
"col_time": L("Typical time", "Typische Dauer", "Durée typique", "Tiempo típico", "المدة النموذجية", "一般的な時間"),
"col_start": L("SpoolDry start", "SpoolDry-Start", "Départ SpoolDry", "Inicio SpoolDry", "بداية SpoolDry", "SpoolDry初期値"),
"col_sources": L("Sources", "Quellen", "Sources", "Fuentes", "المصادر", "出典"),
"safety_h": L("Safety", "Sicherheit", "Sécurité", "Seguridad", "السلامة", "安全"),
"safety_intro": L("SpoolDry hardware is a hobby / prototyping project. It is not certified (no CE, UL or similar). You build and operate it at your own risk.",
                  "SpoolDry-Hardware ist ein Hobby-/Prototypenprojekt. Sie ist nicht zertifiziert (kein CE, UL o. Ä.). Bau und Betrieb auf eigene Gefahr.",
                  "Le matériel SpoolDry est un projet amateur / prototype. Il n'est pas certifié (ni CE, ni UL). Vous le construisez et l'utilisez à vos risques.",
                  "El hardware SpoolDry es un proyecto aficionado / prototipo. No está certificado (sin CE, UL ni similares). Lo construyes y usas bajo tu responsabilidad.",
                  "عتاد SpoolDry مشروع هواة/نموذج أولي وغير معتمد (لا CE ولا UL ولا ما يماثلهما). تبنيه وتشغله على مسؤوليتك.",
                  "SpoolDryハードウェアはホビー/試作プロジェクトであり、認証（CE、ULなど）は受けていません。組み立てと使用は自己責任です。"),
"safety_items": L(
  ["Never bypass the thermal fuse or the thermostat.", "Never operate damaged wiring or connectors.", "Use the specified, certified 24 V power supply.", "Do not exceed the heater, wire and connector ratings.", "Keep flammable materials away from exposed heating elements.", "Use a proper, heat-rated enclosure; keep electronics outside the hot zone.", "Use independent thermal protection in addition to the firmware.", "Do not leave an experimental prototype unattended."],
  ["Thermosicherung und Thermostat niemals überbrücken.", "Niemals mit beschädigten Leitungen oder Steckern betreiben.", "Das angegebene, zertifizierte 24-V-Netzteil verwenden.", "Nennwerte von Heizung, Leitungen und Steckern nicht überschreiten.", "Brennbare Materialien von offenen Heizelementen fernhalten.", "Ein geeignetes, hitzebeständiges Gehäuse nutzen; Elektronik außerhalb der heißen Zone.", "Zusätzlich zur Firmware einen unabhängigen Temperaturschutz verwenden.", "Einen experimentellen Prototyp nie unbeaufsichtigt lassen."],
  ["Ne contournez jamais le fusible thermique ni le thermostat.", "N'utilisez jamais un câblage ou des connecteurs endommagés.", "Utilisez l'alimentation 24 V certifiée indiquée.", "Ne dépassez pas les valeurs du chauffage, des fils et connecteurs.", "Éloignez les matériaux inflammables des éléments chauffants.", "Utilisez un boîtier adapté et résistant à la chaleur ; électronique hors zone chaude.", "Ajoutez une protection thermique indépendante du firmware.", "Ne laissez pas un prototype expérimental sans surveillance."],
  ["Nunca puentees el fusible térmico ni el termostato.", "Nunca uses cableado o conectores dañados.", "Usa la fuente de 24 V certificada indicada.", "No superes los valores nominales del calefactor, cables y conectores.", "Mantén los materiales inflamables lejos de los elementos calefactores.", "Usa una caja adecuada y resistente al calor; la electrónica fuera de la zona caliente.", "Usa protección térmica independiente además del firmware.", "No dejes un prototipo experimental sin vigilancia."],
  ["لا تتجاوز أبدًا المصهر الحراري أو الترموستات.", "لا تشغّل أبدًا بأسلاك أو موصلات تالفة.", "استخدم مزود 24 V المعتمد المحدد.", "لا تتجاوز تصنيفات السخان والأسلاك والموصلات.", "أبعد المواد القابلة للاشتعال عن عناصر التسخين المكشوفة.", "استخدم حاوية مناسبة مقاومة للحرارة وأبقِ الإلكترونيات خارج المنطقة الساخنة.", "استخدم حماية حرارية مستقلة إضافة إلى البرنامج الثابت.", "لا تترك نموذجًا أوليًا تجريبيًا دون مراقبة."],
  ["温度ヒューズやサーモスタットを絶対にバイパスしないこと。", "損傷した配線やコネクタで使用しないこと。", "指定の認証済み24 V電源を使用すること。", "ヒーター、配線、コネクタの定格を超えないこと。", "露出した発熱体の近くに可燃物を置かないこと。", "適切な耐熱ケースを使い、電子回路は高温部の外に置くこと。", "ファームウェアに加えて独立した温度保護を使うこと。", "試作機を放置しないこと。"]),
"layers_h": L("Protection layers", "Schutzebenen", "Couches de protection", "Capas de protección", "طبقات الحماية", "保護レイヤー"),
"pricing_h": L("Simple pricing", "Einfacher Preis", "Tarif simple", "Precio sencillo", "سعر بسيط", "シンプルな料金"),
"free_h": L("Free", "Gratis", "Gratuit", "Gratis", "مجاني", "無料"),
"free_p": L("3 complete drying sessions with every feature, one dryer.", "3 vollständige Trocknungen mit allen Funktionen, ein Trockner.", "3 séchages complets avec toutes les fonctions, un sécheur.", "3 secados completos con todas las funciones, un secador.", "3 جلسات تجفيف كاملة بكل الميزات ومجفف واحد.", "全機能で3回の乾燥セッション、ドライヤー1台。"),
"life_h": L("SpoolDry Lifetime", "SpoolDry Lifetime", "SpoolDry à vie", "SpoolDry de por vida", "SpoolDry مدى الحياة", "SpoolDry 永久ライセンス"),
"life_p": L("Unlimited sessions, multiple dryers, all future improvements. $19.99 in the US App Store; local prices are shown by the App Store.", "Unbegrenzte Trocknungen, mehrere Trockner, alle künftigen Verbesserungen. Lokaler Preis wird im App Store angezeigt (US: 19,99 $).", "Séchages illimités, plusieurs sécheurs, toutes les améliorations. Prix local affiché par l'App Store (US : 19,99 $).", "Secados ilimitados, varios secadores, todas las mejoras. El App Store muestra el precio local (EE. UU.: 19,99 $).", "جلسات غير محدودة وعدة مجففات وكل التحسينات. يعرض App Store السعر المحلي (الولايات المتحدة: 19.99 $).", "無制限のセッション、複数ドライヤー、今後の改善すべて。現地価格はApp Storeに表示（米国：19.99ドル）。"),
"faq_h": L("Frequently asked questions", "Häufige Fragen", "Questions fréquentes", "Preguntas frecuentes", "الأسئلة الشائعة", "よくある質問"),
"faq": L(
  [("Do I need an internet connection or an account?", "No. SpoolDry talks to your dryer over Bluetooth LE. There is no account, no server and no cloud."),
   ("What happens if my iPhone disconnects during drying?", "The ESP32 keeps running the session on its own with all safety limits. When you come back, SpoolDry reconnects and updates history, widgets and the Live Activity."),
   ("Which hardware do I need?", "An Espressif ESP32-C6-DevKitC-1, a Sensirion SHT40 sensor, a 24 V PTC heater, a San Ace 80 fan, logic-level MOSFETs, a relay, an 85 °C thermostat, a 100 °C thermal cutoff and a Mean Well 24 V adapter. See the full BOM above."),
   ("How hot can SpoolDry dry?", "Hardware v1 is limited to 70 °C chamber temperature (fan rating). That covers PLA, PETG, ABS, ASA, TPU, PA, PC and fiber-filled grades. PEEK, PEI and PPS need 110–150 °C and a dedicated dryer or vacuum oven."),
   ("What counts as a free session?", "A session counts when your dryer confirms the start command. Failed attempts, app launches and timer views never count. After 3 sessions, SpoolDry Lifetime unlocks unlimited use."),
   ("Is the drying data official?", "No. The built-in values are typical starting guidance summarised from manufacturer pages (linked). Always follow your filament's data sheet.")],
  [("Brauche ich Internet oder ein Konto?", "Nein. SpoolDry spricht per Bluetooth LE mit deinem Trockner. Kein Konto, kein Server, keine Cloud."),
   ("Was passiert, wenn das iPhone während der Trocknung die Verbindung verliert?", "Der ESP32 führt die Trocknung mit allen Sicherheitsgrenzen selbstständig weiter. Bei Rückkehr verbindet sich SpoolDry neu und aktualisiert Verlauf, Widgets und Live-Aktivität."),
   ("Welche Hardware brauche ich?", "Ein Espressif ESP32-C6-DevKitC-1, einen Sensirion-SHT40-Sensor, eine 24-V-PTC-Heizung, einen San-Ace-80-Lüfter, Logic-Level-MOSFETs, ein Relais, ein 85-°C-Thermostat, eine 100-°C-Thermosicherung und ein Mean-Well-24-V-Netzteil. Siehe Stückliste oben."),
   ("Wie heiß kann SpoolDry trocknen?", "Hardware v1 ist auf 70 °C Kammertemperatur begrenzt (Lüfterspezifikation). Das reicht für PLA, PETG, ABS, ASA, TPU, PA, PC und faserverstärkte Typen. PEEK, PEI und PPS brauchen 110–150 °C."),
   ("Was zählt als Gratis-Trocknung?", "Eine Trocknung zählt, wenn der Trockner den Startbefehl bestätigt. Fehlversuche, App-Starts und Timer-Ansichten zählen nie. Nach 3 Trocknungen schaltet Lifetime alles frei."),
   ("Sind die Trocknungswerte offiziell?", "Nein. Die Werte sind typische Startwerte, zusammengefasst aus (verlinkten) Herstellerseiten. Folge immer dem Datenblatt.")],
  [("Faut-il internet ou un compte ?", "Non. SpoolDry communique avec le sécheur en Bluetooth LE. Pas de compte, pas de serveur, pas de cloud."),
   ("Que se passe-t-il si l'iPhone se déconnecte pendant le séchage ?", "L'ESP32 poursuit seul le séchage avec toutes les limites de sécurité. À votre retour, SpoolDry se reconnecte et met à jour l'historique, les widgets et l'activité en direct."),
   ("Quel matériel faut-il ?", "Une carte Espressif ESP32-C6-DevKitC-1, un capteur Sensirion SHT40, un chauffage PTC 24 V, un ventilateur San Ace 80, des MOSFET logiques, un relais, un thermostat 85 °C, un fusible thermique 100 °C et un bloc Mean Well 24 V. Voir la nomenclature."),
   ("Jusqu'à quelle température ?", "Le matériel v1 est limité à 70 °C dans la chambre (ventilateur). Cela couvre PLA, PETG, ABS, ASA, TPU, PA, PC et grades chargés. PEEK, PEI et PPS nécessitent 110–150 °C."),
   ("Qu'est-ce qu'une séance gratuite ?", "Une séance compte quand le sécheur confirme le démarrage. Les échecs, lancements de l'app et consultations du minuteur ne comptent jamais."),
   ("Les données de séchage sont-elles officielles ?", "Non. Ce sont des repères typiques résumés des pages fabricants (liées). Suivez toujours la fiche technique.")],
  [("¿Necesito internet o una cuenta?", "No. SpoolDry habla con tu secador por Bluetooth LE. Sin cuenta, sin servidor y sin nube."),
   ("¿Qué pasa si el iPhone se desconecta durante el secado?", "El ESP32 sigue con la sesión por sí solo con todos los límites de seguridad. Al volver, SpoolDry se reconecta y actualiza historial, widgets y Actividad en vivo."),
   ("¿Qué hardware necesito?", "Una Espressif ESP32-C6-DevKitC-1, un sensor Sensirion SHT40, un calefactor PTC de 24 V, un ventilador San Ace 80, MOSFET lógicos, un relé, un termostato de 85 °C, un fusible térmico de 100 °C y un adaptador Mean Well de 24 V. Consulta la lista."),
   ("¿Hasta qué temperatura seca?", "El hardware v1 se limita a 70 °C en la cámara (ventilador). Cubre PLA, PETG, ABS, ASA, TPU, PA, PC y grados con fibra. PEEK, PEI y PPS necesitan 110–150 °C."),
   ("¿Qué cuenta como sesión gratuita?", "Cuenta cuando el secador confirma el inicio. Intentos fallidos, aperturas de la app y vistas del temporizador nunca cuentan."),
   ("¿Los datos de secado son oficiales?", "No. Son pautas típicas resumidas de páginas de fabricantes (enlazadas). Sigue siempre la ficha técnica.")],
  [("هل أحتاج إلى إنترنت أو حساب؟", "لا. يتواصل SpoolDry مع المجفف عبر Bluetooth LE. بلا حساب ولا خادم ولا سحابة."),
   ("ماذا يحدث إذا انقطع اتصال الـ iPhone أثناء التجفيف؟", "يواصل ESP32 الجلسة بنفسه مع كل حدود السلامة. عند عودتك يعيد SpoolDry الاتصال ويحدّث السجل والأدوات والنشاط المباشر."),
   ("ما العتاد الذي أحتاجه؟", "لوحة Espressif ESP32-C6-DevKitC-1 وحساس Sensirion SHT40 وسخان PTC بجهد 24 V ومروحة San Ace 80 وترانزستورات MOSFET منطقية ومرحّل وترموستات 85 °C ومصهر حراري 100 °C ومحول Mean Well بجهد 24 V. راجع قائمة المكونات."),
   ("ما أقصى حرارة للتجفيف؟", "العتاد v1 محدود بحرارة 70 °C للحجرة (تصنيف المروحة). يكفي لـ PLA وPETG وABS وASA وTPU وPA وPC والأنواع المدعمة بالألياف. تحتاج PEEK وPEI وPPS إلى 110–150 °C."),
   ("ما الذي يُحتسب جلسة مجانية؟", "تُحتسب الجلسة عندما يؤكد المجفف أمر البدء. المحاولات الفاشلة وفتح التطبيق وعرض المؤقت لا تُحتسب أبدًا."),
   ("هل بيانات التجفيف رسمية؟", "لا. القيم إرشادات نموذجية ملخّصة من صفحات المصنّعين (مرتبطة). اتبع دائمًا ورقة البيانات.")],
  [("インターネットやアカウントは必要ですか？", "いいえ。SpoolDryはBluetooth LEでドライヤーと通信します。アカウント、サーバー、クラウドはありません。"),
   ("乾燥中にiPhoneが切断されたら？", "ESP32がすべての安全制限を保ったままセッションを継続します。戻るとSpoolDryが再接続し、履歴、ウィジェット、ライブアクティビティを更新します。"),
   ("必要なハードウェアは？", "Espressif ESP32-C6-DevKitC-1、Sensirion SHT40、24 V PTCヒーター、San Ace 80ファン、ロジックレベルMOSFET、リレー、85 °Cサーモスタット、100 °C温度ヒューズ、Mean Well 24 Vアダプター。上記の部品表を参照。"),
   ("何度まで乾燥できますか？", "ハードウェアv1は庫内70 °Cまで（ファン定格）。PLA、PETG、ABS、ASA、TPU、PA、PC、繊維入りグレードに対応。PEEK、PEI、PPSは110〜150 °Cが必要です。"),
   ("無料セッションの数え方は？", "ドライヤーが開始コマンドを確認したときにカウントされます。失敗、アプリ起動、タイマー表示はカウントされません。"),
   ("乾燥データは公式ですか？", "いいえ。メーカーページ（リンクあり）を要約した一般的な初期目安です。必ずデータシートに従ってください。")]),
"footer_privacy": L("Privacy", "Datenschutz", "Confidentialité", "Privacidad", "الخصوصية", "プライバシー"),
"footer_support": L("Support", "Support", "Assistance", "Soporte", "الدعم", "サポート"),
"footer_note": L("SpoolDry hardware is a DIY project, not a certified appliance. App made by Tarık Davulcu.", "SpoolDry-Hardware ist ein DIY-Projekt, kein zertifiziertes Gerät. App von Tarık Davulcu.", "Le matériel SpoolDry est un projet DIY, pas un appareil certifié. App par Tarık Davulcu.", "El hardware SpoolDry es un proyecto DIY, no un aparato certificado. App de Tarık Davulcu.", "عتاد SpoolDry مشروع صنع ذاتي وليس جهازًا معتمدًا. التطبيق من تطوير Tarık Davulcu.", "SpoolDryハードウェアはDIYプロジェクトであり、認証製品ではありません。アプリ制作：Tarık Davulcu。"),
"skip": L("Skip to content", "Zum Inhalt", "Aller au contenu", "Ir al contenido", "تخطَّ إلى المحتوى", "本文へ移動"),
"how_h": L("How it works", "So funktioniert es", "Comment ça marche", "Cómo funciona", "كيف يعمل", "仕組み"),
"how": L(["Build the dryer or flash the firmware to your ESP32-C6.", "Pair it with SpoolDry over Bluetooth in seconds.", "Pick a filament profile and start drying. Follow it on your Lock Screen."],
         ["Trockner bauen oder Firmware auf den ESP32-C6 flashen.", "In Sekunden per Bluetooth mit SpoolDry koppeln.", "Filamentprofil wählen, Trocknung starten und auf dem Sperrbildschirm verfolgen."],
         ["Construisez le sécheur ou flashez le firmware sur l'ESP32-C6.", "Jumelez-le à SpoolDry en Bluetooth en quelques secondes.", "Choisissez un profil et lancez le séchage. Suivez-le sur l'écran verrouillé."],
         ["Construye el secador o graba el firmware en el ESP32-C6.", "Empareja con SpoolDry por Bluetooth en segundos.", "Elige un perfil y empieza a secar. Síguelo en la pantalla bloqueada."],
         ["ابنِ المجفف أو حمّل البرنامج الثابت على ESP32-C6.", "اقرنه مع SpoolDry عبر البلوتوث في ثوانٍ.", "اختر ملف الخيط وابدأ التجفيف وتابعه على شاشة القفل."],
         ["ドライヤーを組み立て、ESP32-C6にファームウェアを書き込む。", "BluetoothでSpoolDryと数秒でペアリング。", "プロファイルを選んで乾燥開始。ロック画面で確認。"]),
}
